// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWpqy-JT04cZktyVxwSxgn0b3Us2eOI0Y',
    appId: '1:677037235750:web:90c7b1c9f8e9b8937010e7',
    messagingSenderId: '677037235750',
    projectId: 'kiosk-development-aaec9',
    authDomain: 'kiosk-development-aaec9.firebaseapp.com',
    databaseURL: 'https://kiosk-development-aaec9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kiosk-development-aaec9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsJObDGA8F46Lc0QzQ43PKML1Sas_0bE0',
    appId: '1:677037235750:android:c939bcb107c9139a7010e7',
    messagingSenderId: '677037235750',
    projectId: 'kiosk-development-aaec9',
    databaseURL: 'https://kiosk-development-aaec9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kiosk-development-aaec9.firebasestorage.app',
  );
}
